### ISSUE TITLE
Video don’t auto start

### ISSUE THREAD

**Issue by GrayJack** [rahmanshaber/corebox#3]
When I try to open a video from CoreFM in CorePlayer the video don’t auto start, actually, I have to open the side tab with the recent opened files and click in the file to start to play.

Version used: 2.0.0

**Comment by rahmanshaber** [comment]
i know that issue.it is on fix list.

**Comment by rahmanshaber** [comment]
it is fixed now.
next version will have the fix.
version 2.1 will bring many fix and feture .
please try it out.
