### ISSUE TITLE
CoreFM keeps the folder names in white making impossible to read

### ISSUE THREAD

**Issue by GrayJack** [rahmanshaber/corebox#4]
CoreFM keeps the folder names in white making impossible to read, but other files the name is in black and readable
![screenshot-2018-03-27](https://user-images.githubusercontent.com/17973728/37997090-4c912078-31f0-11e8-9566-9b45fcbdca50.png)

Version used: 2.0.0

**Comment by rahmanshaber** [comment]
i didn't thought that could be happen.i think your using breeze icon.we will add dark and white theme in corefm in next release.i hope that will solve the problem .for now use other theme by changing from corebox setting.
thanks.

**Comment by rahmanshaber** [comment]
i relesed a new version CoreBox-v2.2.
In this relese we included two mode Dark & Light.
so there is no issue in seeing the text of corefm.
![u](https://user-images.githubusercontent.com/30831735/43310991-fb1eb6e0-91aa-11e8-84b7-2fa343a753dc.png)

as it is solved ,i am closing this issue.
thanks.
