### ISSUE TITLE
[Travis] Project ERROR: Unknown module(s) in QT: webengine webenginecore webenginewidgets webchannel

### ISSUE THREAD

**Issue by hphilm** [rahmanshaber/corebox#7]
Seems to be a dependency issue holding **Travis** back from compiling. Look [here](https://launchpad.net/ubuntu/+source/qtwebengine-opensource-src) for the package names and add them as needed to your yaml file.

**Comment by rahmanshaber** [comment]
ok.
i included those packages .
but now it tells me can't install

**Comment by hphilm** [comment]
@rahmanshaber: it seems ubuntu and deb-packages is new for you. Did you checked [which packages](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt593-trusty) are available? Try it with **qt59webengine**.

**Comment by rahmanshaber** [comment]
ok. this time i got it build.

**Comment by rahmanshaber** [comment]
hello . 
i found that it dose not builds fine.
someone told me it is a compiler error .
but i don't know how to fix that.
if you can help me that will be great.
